GET http://0.0.0.0:8080/news

###

POST http://0.0.0.0:8080/news
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache

{
  "id": 1,
  "title": "...",
  "summary": "...",
  "date": "...",
  "imageUrl": "...",
  "content": "...",
  "editor": "..."
}
